[".vim/bundle/vim-pathogen"]
type="git-repo"
url="https://github.com/tpope/vim-pathogen.git"

[".vim/bundle/rust.vim"]
type="git-repo"
url="https://github.com/rust-lang/rust.vim.git"

[".vim/bundle/vim-bracketed-paste"]
type="git-repo"
url="https://github.com/ConradIrwin/vim-bracketed-paste"

[".vim/bundle/vim-sensible"]
type="git-repo"
url="https://github.com/tpope/vim-sensible.git"

[".vim/bundle/vim-sleuth"]
type="git-repo"
url="https://github.com/tpope/vim-sleuth.git"

[".vim/bundle/chezmoi.vim"]
type="git-repo"
url="https://github.com/alker0/chezmoi.vim.git"

